# Generated by Django 3.2.7 on 2021-09-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardocument',
            name='document_type',
            field=models.CharField(choices=[('tech_passport', 'Tech Passport'), ('document_1', 'Document 1'), ('document_2', 'Document 2'), ('special_document', 'Special Document')], default='tech_passport', max_length=50),
        ),
    ]
